# Generated by Django 5.2.7 on 2025-10-29 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='account_use_is_acti_428f36_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'id'], name='account_use_is_acti_0a59de_idx'),
        ),
        migrations.AddField(
            model_name='diary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
