# Generated by Django 5.2.7 on 2025-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_diary_remove_user_account_use_is_acti_428f36_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['id'], name='account_dia_id_bcf98b_idx'),
        ),
    ]
